from dagster import asset, FreshnessPolicy
import pandas as pd
import os

def handle_request(year):
    BASE_URL = 'https://financialmodelingprep.com/api/v4/'
    url = BASE_URL + f'key-metrics-bulk?year={year}&+&period=quarter&datatype=csv&apikey=' + os.environ['FMP_API_KEY']
    df = pd.read_csv(url)
    
    column_name_mapping = 	{
	    "symbol": "symbol",
	    "date": "date",
	    "period": "period",
	    "revenuePerShare": "revenue_per_share",
	    "netIncomePerShare": "net_income_per_share",
	    "operatingCashFlowPerShare": "operating_cash_flow_per_share",
	    "freeCashFlowPerShare": "free_cash_flow_per_share",
	    "cashPerShare": "cash_per_share",
	    "bookValuePerShare": "book_value_per_share",
	    "tangibleBookValuePerShare": "tangible_book_value_per_share",
	    "shareholdersEquityPerShare": "shareholders_equity_per_share",
	    "interestDebtPerShare": "interest_debt_per_share",
	    "marketCap": "market_cap",
	    "enterpriseValue": "enterprise_value",
	    "peRatio": "pe_ratio",
	    "priceToSalesRatio": "price_to_sales_ratio",
	    "pocfratio": "pocfratio",
	    "pfcfRatio": "pfcf_ratio",
	    "pbRatio": "pb_ratio",
	    "ptbRatio": "ptb_ratio",
	    "evToSales": "ev_to_sales",
	    "enterpriseValueOverEBITDA": "enterprise_value_over_e_b_i_t_d_a",
	    "evToOperatingCashFlow": "ev_to_operating_cash_flow",
	    "earningsYield": "earnings_yield",
	    "freeCashFlowYield": "free_cash_flow_yield",
	    "debtToEquity": "debt_to_equity",
	    "debtToAssets": "debt_to_assets",
	    "netDebtToEBITDA": "net_debt_to_e_b_i_t_d_a",
	    "currentRatio": "current_ratio",
	    "interestCoverage": "interest_coverage",
	    "incomeQuality": "income_quality",
	    "dividendYield": "dividend_yield",
	    "payoutRatio": "payout_ratio",
	    "salesGeneralAndAdministrativeToRevenue": "sales_general_and_administrative_to_revenue",
	    "researchAndDdevelopementToRevenue": "research_and_ddevelopement_to_revenue",
	    "intangiblesToTotalAssets": "intangibles_to_total_assets",
	    "capexToOperatingCashFlow": "capex_to_operating_cash_flow",
	    "capexToRevenue": "capex_to_revenue",
	    "capexToDepreciation": "capex_to_depreciation",
	    "stockBasedCompensationToRevenue": "stock_based_compensation_to_revenue",
	    "grahamNumber": "graham_number",
	    "roic": "roic",
	    "returnOnTangibleAssets": "return_on_tangible_assets",
	    "grahamNetNet": "graham_net_net",
	    "workingCapital": "working_capital",
	    "tangibleAssetValue": "tangible_asset_value",
	    "netCurrentAssetValue": "net_current_asset_value",
	    "investedCapital": "invested_capital",
	    "averageReceivables": "average_receivables",
	    "averagePayables": "average_payables",
	    "averageInventory": "average_inventory",
	    "daysSalesOutstanding": "days_sales_outstanding",
	    "daysPayablesOutstanding": "days_payables_outstanding",
	    "daysOfInventoryOnHand": "days_of_inventory_on_hand",
	    "receivablesTurnover": "receivables_turnover",
	    "payablesTurnover": "payables_turnover",
	    "inventoryTurnover": "inventory_turnover",
	    "roe": "roe",
	    "capexPerShare": "capex_per_share",
	    "calendarYear": "calendar_year"
	}
    df = df.rename(columns=column_name_mapping)
    df['date'] = pd.to_datetime(df['date']).dt.date
    return df

@asset(
    metadata={
        "source": "Financial Modeling Prep",
        "name": "Key Metrics Data",
        "description": "Retrieves and transforms key financial metrics data for multiple years into a structured format, focusing on various financial ratios and values critical for financial analysis.",
        "columns": [
            {"name": "symbol", "description": "Ticker symbol of the company."},
            {"name": "date", "description": "Date of the financial data."},
            {"name": "period", "description": "Financial reporting period."},
            {"name": "revenue_per_share", "description": "Revenue per share."},
            {"name": "net_income_per_share", "description": "Net income per share."},
            {"name": "operating_cash_flow_per_share", "description": "Operating cash flow per share."},
            {"name": "free_cash_flow_per_share", "description": "Free cash flow per share."},
            {"name": "cash_per_share", "description": "Cash per share."},
            {"name": "book_value_per_share", "description": "Book value per share."},
            {"name": "tangible_book_value_per_share", "description": "Tangible book value per share."},
            {"name": "shareholders_equity_per_share", "description": "Shareholders' equity per share."},
            {"name": "interest_debt_per_share", "description": "Interest-bearing debt per share."},
            {"name": "market_cap", "description": "Market capitalization."},
            {"name": "enterprise_value", "description": "Enterprise value."},
            {"name": "pe_ratio", "description": "Price-to-Earnings ratio."},
            {"name": "price_to_sales_ratio", "description": "Price-to-Sales ratio."},
            {"name": "pocfratio", "description": "Price to Operating Cash Flow ratio."},
            {"name": "pfcf_ratio", "description": "Price to Free Cash Flow ratio."},
            {"name": "pb_ratio", "description": "Price-to-Book ratio."},
            {"name": "ptb_ratio", "description": "Price-to-Tangible-Book ratio."},
            {"name": "ev_to_sales", "description": "Enterprise Value to Sales ratio."},
            {"name": "enterprise_value_over_e_b_i_t_d_a", "description": "Enterprise Value over EBITDA."},
            {"name": "ev_to_operating_cash_flow", "description": "Enterprise Value to Operating Cash Flow ratio."},
            {"name": "earnings_yield", "description": "Earnings yield."},
            {"name": "free_cash_flow_yield", "description": "Free Cash Flow yield."},
            {"name": "debt_to_equity", "description": "Debt to Equity ratio."},
            {"name": "debt_to_assets", "description": "Debt to Assets ratio."},
            {"name": "net_debt_to_e_b_i_t_d_a", "description": "Net Debt to EBITDA ratio."},
            {"name": "current_ratio", "description": "Current ratio."},
            {"name": "interest_coverage", "description": "Interest Coverage ratio."},
            {"name": "income_quality", "description": "Income quality."},
            {"name": "dividend_yield", "description": "Dividend yield."},
            {"name": "payout_ratio", "description": "Payout ratio."},
            {"name": "sales_general_and_administrative_to_revenue", "description": "Sales, General, and Administrative expenses to Revenue ratio."},
            {"name": "research_and_ddevelopement_to_revenue", "description": "Research and Development to Revenue ratio."},
            {"name": "intangibles_to_total_assets", "description": "Intangibles to Total Assets ratio."},
            {"name": "capex_to_operating_cash_flow", "description": "Capital Expenditures to Operating Cash Flow ratio."},
            {"name": "capex_to_revenue", "description": "Capital Expenditures to Revenue ratio."},
            {"name": "capex_to_depreciation", "description": "Capital Expenditures to Depreciation ratio."},
            {"name": "stock_based_compensation_to_revenue", "description": "Stock-Based Compensation to Revenue ratio."},
            {"name": "graham_number", "description": "Graham number."},
            {"name": "roic", "description": "Return on Invested Capital."},
            {"name": "return_on_tangible_assets", "description": "Return on Tangible Assets."},
            {"name": "graham_net_net", "description": "Graham Net-Net."},
            {"name": "working_capital", "description": "Working capital."},
            {"name": "tangible_asset_value", "description": "Tangible asset value."},
            {"name": "net_current_asset_value", "description": "Net current asset value."},
            {"name": "invested_capital", "description": "Invested capital."},
            {"name": "average_receivables", "description": "Average receivables."},
            {"name": "average_payables", "description": "Average payables."},
            {"name": "average_inventory", "description": "Average inventory."},
            {"name": "days_sales_outstanding", "description": "Days Sales Outstanding."},
            {"name": "days_payables_outstanding", "description": "Days Payables Outstanding."},
            {"name": "days_of_inventory_on_hand", "description": "Days of Inventory on Hand."},
            {"name": "receivables_turnover", "description": "Receivables Turnover."},
            {"name": "payables_turnover", "description": "Payables Turnover."},
            {"name": "inventory_turnover", "description": "Inventory Turnover."},
            {"name": "roe", "description": "Return on Equity."},
            {"name": "capex_per_share", "description": "Capital Expenditures per share."},
            {"name": "calendar_year", "description": "Calendar year of the report."}
        ]
    },
    freshness_policy=FreshnessPolicy(maximum_lag_minutes=60 * 24 * 30, cron_schedule="0 0 1 * *")
)
def fmp_key_metrics():
    dfs = [handle_request(year) for year in range(1985, 2023)]
    df = pd.concat(dfs)
    df = df.dropna(how='all')
    return df
