FROM python:3.11-slim

RUN pip install \
    dagster \
    dagster-graphql \
    dagster-webserver \
    dagster-postgres \
    dagster-docker

ENV DAGSTER_HOME=/opt/dagster/app

RUN mkdir -p $DAGSTER_HOME

COPY workspace.yaml $DAGSTER_HOME

WORKDIR $DAGSTER_HOME